# Generated by Django 3.1 on 2020-08-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=15, null=True)),
                ('code', models.TextField(blank=True, max_length=15, null=True)),
                ('modelYear', models.TextField(blank=True, max_length=15, null=True)),
                ('capacityKg', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('capacityLbs', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('OpeningRangeMmMin', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('OpeningRangeMmMax', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('OpeningRangeInMin', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('OpeningRangeInMax', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sideShiftMm', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sideShiftIn', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('bodyRotation', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('PadsRotation', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('DesignType', models.TextField(default='flat', max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tyrehandler/')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('priceToman', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('priceDollar', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
