# Generated by Django 3.1 on 2020-08-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyrehandler',
            name='DesignType',
            field=models.CharField(choices=[('flat', 'flat clamp'), ('telescopic', 'telescopic'), ('parallelogram', 'parallelogram')], default='flat', max_length=15),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='modelYear',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
