# Generated by Django 3.1 on 2020-08-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200807_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='capacityKg',
            new_name='capacity_Kg',
        ),
    ]
