# Generated by Django 3.1 on 2020-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200807_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyrehandler',
            name='modelYear',
        ),
        migrations.AddField(
            model_name='tyrehandler',
            name='model_Year',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
