# Generated by Django 3.1 on 2020-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200807_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('model_Year', models.CharField(blank=True, max_length=6, null=True)),
                ('capacity_Kg', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('capacity_Lbs', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Cylinder_Diameter_mm_min', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Cylinder_Diameter_mm_max', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Cylinder_Diameter_in_min', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Cylinder_Diameter_in_max', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sideShift_Mm', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('sideShift_In', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('body_Rotation', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Handler_tilting', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tyrehandler/')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('price_Toman', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('price_Dollar', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='DesignType',
            new_name='Design_Type',
        ),
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='PadsRotation',
            new_name='Pads_Rotation',
        ),
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='bodyRotation',
            new_name='body_Rotation',
        ),
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='priceDollar',
            new_name='price_Dollar',
        ),
        migrations.RenameField(
            model_name='tyrehandler',
            old_name='priceToman',
            new_name='price_Toman',
        ),
    ]
