# Generated by Django 3.1 on 2020-08-07 20:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200807_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderhandler',
            name='description',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='description',
            field=ckeditor.fields.RichTextField(default='alo'),
            preserve_default=False,
        ),
    ]
