# Generated by Django 3.1 on 2020-08-08 07:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200807_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderhandler',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
