# Generated by Django 3.1 on 2020-08-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200808_0724'),
        ('website', '0010_auto_20200808_1149'),
    ]

    operations = [
    ]
