# Generated by Django 3.1 on 2020-08-08 10:47

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_merge_20200808_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=website.models.CylinderHandler, to='website.struthandler')),
            ],
        ),
    ]
