# Generated by Django 3.1 on 2020-08-08 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200808_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderHandlerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cylinderhandlerImagesProduct/')),
                ('cylinderhandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cylinderhandler')),
            ],
        ),
        migrations.CreateModel(
            name='StruthandlerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='struthandlerImagesProduct/')),
                ('struthandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.struthandler')),
            ],
        ),
        migrations.CreateModel(
            name='tyreHandlerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tyreHandlerImagesProduct/')),
                ('tyreHandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.tyrehandler')),
            ],
        ),
        migrations.DeleteModel(
            name='milad',
        ),
        migrations.DeleteModel(
            name='mm',
        ),
    ]
