# Generated by Django 3.1 on 2020-08-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200808_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='category/')),
            ],
        ),
        migrations.AddField(
            model_name='cylinderhandler',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AddField(
            model_name='struthandler',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AddField(
            model_name='tyrehandler',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
