# Generated by Django 3.1 on 2020-08-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200808_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cylinderhandler',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AlterField(
            model_name='struthandler',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category'),
        ),
    ]
