# Generated by Django 3.1 on 2020-08-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200808_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cylinderhandler',
            name='type',
        ),
        migrations.RemoveField(
            model_name='struthandler',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tyrehandler',
            name='type',
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
