# Generated by Django 3.1 on 2020-08-20 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('model_Year', models.CharField(blank=True, max_length=6, null=True)),
                ('capacity_Kg', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('capacity_Lbs', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Roll_Diameter_mm', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('Roll_Diameter_in', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('articulation', models.CharField(blank=True, max_length=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='belthandler/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price_Toman', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('price_Dollar', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
        migrations.CreateModel(
            name='PipeHandler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('model_Year', models.CharField(blank=True, max_length=6, null=True)),
                ('capacity_Kg', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('capacity_Lbs', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('range_diameter_mm', models.CharField(blank=True, max_length=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheelmotor/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price_Toman', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('price_Dollar', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
        migrations.CreateModel(
            name='Wheelmotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('model_Year', models.CharField(blank=True, max_length=6, null=True)),
                ('capacity_Kg', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('capacity_Lbs', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='wheelmotor/')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price_Toman', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('price_Dollar', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
        ),
        migrations.AlterField(
            model_name='cylinderhandler',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='struthandler',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tyrehandler',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='WheelmotorImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wheelmotorImagesProduct/')),
                ('struthandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.wheelmotor')),
            ],
        ),
        migrations.CreateModel(
            name='PipeHandlerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pipehandlerImagesProduct/')),
                ('struthandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pipehandler')),
            ],
        ),
        migrations.CreateModel(
            name='BeltHandlerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='belthandlerImagesProduct/')),
                ('struthandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.belthandler')),
            ],
        ),
    ]
