# Generated by Django 3.1 on 2020-09-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_cablehandler_cablehandlerimages_rodhandler_rodhandlerimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cablehandlerimages',
            name='cablehandler',
        ),
        migrations.RemoveField(
            model_name='cylinderhandlerimages',
            name='cylinderhandler',
        ),
        migrations.RemoveField(
            model_name='pipehandlerimages',
            name='struthandler',
        ),
        migrations.RemoveField(
            model_name='rodhandlerimages',
            name='rodhandler',
        ),
        migrations.RemoveField(
            model_name='struthandlerimages',
            name='struthandler',
        ),
        migrations.RemoveField(
            model_name='tyrehandlerimages',
            name='tyreHandler',
        ),
        migrations.RemoveField(
            model_name='wheelmotorimages',
            name='struthandler',
        ),
        migrations.AddField(
            model_name='belthandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='belthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='belthandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='belthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='belthandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='belthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cablehandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cablehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cablehandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cablehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cablehandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cablehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cylinderhandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='cylinderhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cylinderhandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='cylinderhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='cylinderhandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='cylinderhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='pipehandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='pipehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='pipehandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='pipehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='pipehandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='pipehandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='rodhandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rodhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='rodhandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rodhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='rodhandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rodhandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='struthandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='struthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='struthandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='struthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='struthandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='struthandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='tyrehandler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tyreHandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='tyrehandler',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tyreHandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='tyrehandler',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='tyreHandlerImagesProduct/'),
        ),
        migrations.AddField(
            model_name='wheelmotor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='wheelmotorImagesProduct/'),
        ),
        migrations.AddField(
            model_name='wheelmotor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='wheelmotorImagesProduct/'),
        ),
        migrations.AddField(
            model_name='wheelmotor',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='wheelmotorImagesProduct/'),
        ),
        migrations.DeleteModel(
            name='BeltHandlerImages',
        ),
        migrations.DeleteModel(
            name='CableHandlerImages',
        ),
        migrations.DeleteModel(
            name='CylinderHandlerImages',
        ),
        migrations.DeleteModel(
            name='PipeHandlerImages',
        ),
        migrations.DeleteModel(
            name='RodHandlerImages',
        ),
        migrations.DeleteModel(
            name='StruthandlerImages',
        ),
        migrations.DeleteModel(
            name='tyreHandlerImages',
        ),
        migrations.DeleteModel(
            name='WheelmotorImages',
        ),
    ]
